---
title: "Übung 01 - Random-Walk und fraktale Dimension"
author: "Marlene Selbach & Jana Achten"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: 2
lang: de-DE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Einleitung
Im Folgenden ist ein Random-Walk in zwei Dimensionen zu implementieren und über einen Plot zu visualisieren. Ausgangspunkt ist die Iterationsvorschrift

$$
q_{n+1} = \frac{q_n + p_{i_n}}{2},
$$
wobei in jedem Schritt einer der vier Punkte 

$$
p_0 = (0,0), \quad p_1 = (1,0), \quad p_2 = (0,1), \quad p_3 = (1,1)
$$
zufällig ausgewählt wird. Zusätzlich wird verlangt, dass derselbe Index nicht in zwei aufeinanderfolgenden Schritten verwendet werden darf. Als Startwert wird 

$$
q_0 = p_0 = (0,0)
$$
gesetzt.

Ziel der Aufgabe ist es, für eine große Anzahl an Iterationen ($N = 10^6$) die Punkte $q_n$ zu erzeugen und in einem zweidimensionalen Plot darzustellen.



Die Aufgabe wird dabei in zwei Teile gegliedert:
1. In c++ erfolgt die Berechnung des Random-Walks.
2. In Python wird der Random-Walk als Streudiagramm visualisiert.


# Lösung der Aufgabe
## Berechnung in C++
### Definition der Eckpunkte


